name: Release

on:
  push:
    branches:
    - main
    #paths: 
    #- '**.tf'
  #pull_request:
    #branches:
    #- main
    #paths: 
    #- staging/**

permissions:
  contents: read
  pull-requests: write

jobs: 
  infra:
    uses: ./.github/workflows/infra.yaml
    secrets:
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  docker:
    needs: [infra]
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    name: docker
    environment: development

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2    

    - name: Set short git commit SHA
      id: vars
      run: |
        calculatedSha=$(git rev-parse --short ${{ github.sha }})
        echo "::set-output name=short_sha::$calculatedSha"
  
    - name: Deploy to Cluster
      uses: cancue/eks-action@v0.0.2
      env:
        kubeconfig: ${{ secrets.KUBE_CONFIG_DATA }}
        aws_region: us-east-1
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        cluster_name: eks-cluster
      with:
        args: |
          kubectl apply -f ./containers/app/k8s/configmap-nginx.yaml -f ./containers/app/k8s/deployment.yaml